name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install
        run: |
          yarn install

      - name: Build
        run: |
          yarn build

      - name: Linting
        run: |
          yarn lint

      - name: Start app
        run: |
          yarn start &

      - name: Test
        run: |
          yarn test --coverage

      - name: Publish coverage report to Code Climate
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 62abc336acd7f68ce63ee6b504cf0210c445da115e926633662c1c97e0f5740c
        with:
          debug: true
          coverageLocations: coverage/lcov.info:lcov
        continue-on-error: true

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
